### ISSUE TITLE
[CRASH] Votemap caused server crash

### ISSUE THREAD

**Issue by Hembi** [s1lentq/ReGameDLL_CS#360]
ReHLDS version: 3.4.0.671-dev
ReGameDLL version: 5.7.0.330-dev

> Program terminated with signal SIGSEGV, Segmentation fault.
> #0  0xf2dd094a in CHalfLifeMultiplay::DisplayMaps () from /cstrike/dlls/cs.so
> #0  0xf2dd094a in CHalfLifeMultiplay::DisplayMaps () from /cstrike/dlls/cs.so
> #1  0x5f006574 in ?? ()
> #2  0x0077656e in ?? ()
> #3  0x3b3b3b3b in ?? ()
> #4  0x00000000 in ?? ()
> No symbol table info available.
> From        To          Syms Read   Shared Object Library
>                         No          linux-gate.so.1
> 0xf77baad0  0xf77bb96c  Yes (*)     /lib/i386-linux-gnu/i686/cmov/libdl.so.2
> 0xf772d914  0xf7773c78  Yes         ./libstdc++.so.6
> 0xf76a4600  0xf76d1ed5  Yes (*)     /lib/i386-linux-gnu/i686/cmov/libm.so.6
> 0xf750a420  0xf763a6fe  Yes (*)     /lib/i386-linux-gnu/i686/cmov/libc.so.6
> 0xf77d1860  0xf77e980c  Yes (*)     /lib/ld-linux.so.2
> 0xf74dfe04  0xf74ef490  Yes         ./libgcc_s.so.1
> 0xf6e12ee0  0xf6ef7e90  Yes (*)     /engine_i486.so
> 0xf6dd79b0  0xf6ddaeaa  Yes (*)     /lib/i386-linux-gnu/i686/cmov/librt.so.1
> 0xf6dc55c0  0xf6dcfd74  Yes (*)     ./libsteam_api.so
> 0xf6dab840  0xf6db7f57  Yes (*)     /lib/i386-linux-gnu/i686/cmov/libpthread.so.0
> 0xf6d8ef40  0xf6da03f8  Yes (*)     /filesystem_stdio.so
> 0xf5958200  0xf67f13c4  Yes (*)     ./steamclient.so
> 0xf57f7670  0xf586d020  Yes (*)     ./crashhandler.so
> 0xf2fbab70  0xf2fd0984  Yes         /./cstrike/addons/metamod/dlls/metamod.so
> 0xf2d34510  0xf2eaf450  Yes (*)     /cstrike/dlls/cs.so
> 0xf2c29d00  0xf2c2af40  Yes (*)     /cstrike/addons/reunion/SafeNameAndChat.so
> 0xf2a568b0  0xf2ab9967  Yes (*)     /cstrike/addons/amxmodx/dlls/amxmodx_mm_i386.so
> 0xf29f1800  0xf2a20960  Yes (*)     cstrike/addons/amxmodx/modules/reapi_amxx_i386.so
> 0xf29c2130  0xf29c8810  Yes (*)     cstrike/addons/amxmodx/modules/reaimdetector_amxx_i386.so
> 0xf29983a0  0xf29ae370  Yes (*)     /cstrike/addons/reunion/reunion_mm_i386.so
> 0xf296eb40  0xf29780b0  Yes (*)     /cstrike/addons/reunion/reauthcheck_mm_i386.so
> 0xf2951200  0xf2964120  Yes (*)     /cstrike/addons/reunion/rechecker_mm_i386.so
> 0xf2897db0  0xf28b3ec0  Yes (*)     cstrike/addons/whblocker/whblocker_mm_i386.so
> 0xf267a8c0  0xf2828571  Yes (*)     cstrike/addons/voicetranscoder/VoiceTranscoder.so
> 0xf2604d50  0xf2614460  Yes (*)     cstrike/addons/amxmodx/modules/cstrike_amxx_i386.so
> 0xf25f5660  0xf25f9f84  Yes (*)     cstrike/addons/amxmodx/modules/fun_amxx_i386.so
> 0xf25bf9d0  0xf25ebd6c  Yes (*)     cstrike/addons/amxmodx/modules/fakemeta_amxx_i386.so
> 0xf2555b60  0xf259d624  Yes (*)     cstrike/addons/amxmodx/modules/hamsandwich_amxx_i386.so
> 0xf25349b0  0xf2538a08  Yes (*)     cstrike/addons/amxmodx/modules/nvault_amxx_i386.so
> 0xf2522290  0xf252e80c  Yes (*)     cstrike/addons/amxmodx/modules/engine_amxx_i386.so
> 0xf2428120  0xf242e404  Yes (*)     cstrike/addons/amxmodx/modules/csx_amxx_i386.so
> 0xf1fcf790  0xf2067fc5  Yes (*)     cstrike/addons/amxmodx/modules/mysql_amxx_i386.so
> 0xf0ad6ad0  0xf0add8ab  Yes (*)     /lib/i386-linux-gnu/i686/cmov/libnss_files.so.2
> 0xf0acec40  0xf0ad1b9e  Yes (*)     /lib/i386-linux-gnu/i686/cmov/libnss_dns.so.2
> 0xf0ab8720  0xf0ac4db4  Yes (*)     /lib/i386-linux-gnu/i686/cmov/libresolv.so.2
> 0xf24b05d0  0xf24f9548  Yes (*)     cstrike/addons/amxmodx/modules/regex_amxx_i386.so
> 0xf2417f60  0xf241924c  Yes (*)     cstrike/addons/amxmodx/modules/sockets_amxx_i386.so
> (*): Shared library is missing debugging information.
> Stack level 0, frame at 0xff821c24:
>  eip = 0xf2dd094a in _ZN18CHalfLifeMultiplay11DisplayMapsEP11CBasePlayeri.; saved eip = 0x5f006574
>  called by frame at 0xff821c28
>  Arglist at 0xff821c1c, args: 
>  Locals at 0xff821c1c, Previous frame's sp is 0xff821c24
>  Saved registers:
>   ebx at 0xff821c10, ebp at 0xff821c0c, esi at 0xff821c18, edi at 0xff821c14, eip at 0xff821c20
> End of crash report

**Comment by Hembi** [comment]
This lines caused the problem in mapcycle.txt:

> ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
> ;;;                                   ;;;
> ;;; OLD MAPS ;;;
> ;;;                                   ;;;
> ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
