### ISSUE TITLE
Compilation not successful. I do not understand what's going on.

### ISSUE THREAD

**Issue by Uberwire** [s1lentq/ReGameDLL_CS#499]
I am on Windows 7. I've cloned the whole project on my desktop, followed the Build Instructions, however, I'm not that familiar with gradle, but I would really want to modify my own mp.dll for my own unique server. This project looks really interesting and popular.

As I've said, I've cloned the whole project, accessed its root folder with cmd.exe run as Administrator, ran `gradlew --max-workers=1 clean buildRelease` without any additional parameter and got a bunch of exceptions spewed out I really do not understand what they mean.

Here is the output after running the gradlew command.

    :buildSrc:compileJava UP-TO-DATE
    :buildSrc:compileGroovy UP-TO-DATE
    :buildSrc:processResources UP-TO-DATE
    :buildSrc:classes UP-TO-DATE
    :buildSrc:jar UP-TO-DATE
    :buildSrc:assemble UP-TO-DATE
    :buildSrc:compileTestJava UP-TO-DATE
    :buildSrc:compileTestGroovy UP-TO-DATE
    :buildSrc:processTestResources UP-TO-DATE
    :buildSrc:testClasses UP-TO-DATE
    :buildSrc:test UP-TO-DATE
    :buildSrc:check UP-TO-DATE
    :buildSrc:build UP-TO-DATE
    Caught exception in FS.readPipe()
    java.io.IOException: Cannot run program "bash" (in directory "C:\Users\Marko"):
    CreateProcess error=2, The system cannot find the file specified
            at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
            at java.lang.Runtime.exec(Runtime.java:620)
            at org.eclipse.jgit.util.FS.readPipe(FS.java:431)
            at org.eclipse.jgit.util.FS_Win32.discoverGitPrefix(FS_Win32.java:113)
            at org.eclipse.jgit.util.FS.gitPrefix(FS.java:517)
            at org.eclipse.jgit.util.SystemReader$Default.openSystemConfig(SystemRea
    der.java:92)
            at org.eclipse.jgit.internal.storage.file.FileRepository.<init>(FileRepo
    sitory.java:171)
            at org.eclipse.jgit.storage.file.FileRepositoryBuilder.build(FileReposit
    oryBuilder.java:92)
            at versioning.GitVersioner.versionForDir(GitVersioner.groovy:71)
            at versioning.GitVersioner$versionForDir.call(Unknown Source)
            at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSi
    teArray.java:45)
            at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCa
    llSite.java:108)
            at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCa
    llSite.java:116)
            at build_dhlbt543rmful23ohzt8f23az.run(D:\HL Mod Toolkit\cstrike\regamed
    ll\ReGameDLL_CS-master\build.gradle:17)
            at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptR
    unnerImpl.run(DefaultScriptRunnerFactory.java:74)
            at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl$
    1.run(DefaultScriptPluginFactory.java:148)
            at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl.
    apply(DefaultScriptPluginFactory.java:156)
            at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildSc
    riptProcessor.java:39)
            at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildSc
    riptProcessor.java:26)
            at org.gradle.configuration.project.ConfigureActionsProjectEvaluator.eva
    luate(ConfigureActionsProjectEvaluator.java:34)
            at org.gradle.configuration.project.LifecycleProjectEvaluator.evaluate(L
    ifecycleProjectEvaluator.java:55)
            at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProj
    ect.java:487)
            at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProj
    ect.java:85)
            at org.gradle.execution.TaskPathProjectEvaluator.configureHierarchy(Task
    PathProjectEvaluator.java:42)
            at org.gradle.configuration.DefaultBuildConfigurer.configure(DefaultBuil
    dConfigurer.java:35)
            at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(Default
    GradleLauncher.java:129)
            at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradle
    Launcher.java:106)
            at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLaun
    cher.java:86)
            at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildCon
    troller.run(InProcessBuildActionExecuter.java:90)
            at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(Exe
    cuteBuildActionRunner.java:28)
            at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildA
    ctionRunner.java:35)
            at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProce
    ssBuildActionExecuter.java:41)
            at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProce
    ssBuildActionExecuter.java:28)
            at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.exe
    cute(DaemonUsageSuggestingBuildActionExecuter.java:50)
            at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.exe
    cute(DaemonUsageSuggestingBuildActionExecuter.java:27)
            at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:40)
            at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.jav
    a:169)
            at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.
    execute(CommandLineActionFactory.java:237)
            at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.
    execute(CommandLineActionFactory.java:210)
            at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRunti
    meValidationAction.java:35)
            at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRunti
    meValidationAction.java:24)
            at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(
    CommandLineActionFactory.java:206)
            at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(
    CommandLineActionFactory.java:169)
            at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionRep
    ortingAction.java:33)
            at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionRep
    ortingAction.java:22)
            at org.gradle.launcher.Main.doAction(Main.java:33)
            at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
            at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
            at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.
    java:62)
            at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
    sorImpl.java:43)
            at java.lang.reflect.Method.invoke(Method.java:498)
            at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBoots
    trap.java:54)
            at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.j
    ava:35)
            at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
            at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
            at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.
    java:62)
            at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
    sorImpl.java:43)
            at java.lang.reflect.Method.invoke(Method.java:498)
            at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.ja
    va:30)
            at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:127)
            at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
    Caused by: java.io.IOException: CreateProcess error=2, The system cannot find th
    e file specified
            at java.lang.ProcessImpl.create(Native Method)
            at java.lang.ProcessImpl.<init>(ProcessImpl.java:444)
            at java.lang.ProcessImpl.start(ProcessImpl.java:140)
            at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
            ... 60 more
    ##teamcity[buildNumber '5.13.0']
    
    FAILURE: Build failed with an exception.
    
    * Where:
    Script 'D:\HL Mod Toolkit\cstrike\regamedll\ReGameDLL_CS-master\shared.gradle' l
    ine: 47
    
    * What went wrong:
    A problem occurred configuring project ':dep/cppunitlite'.
    > Exception thrown while executing model rule: org.gradle.nativeplatform.plugins
    .NativeComponentModelPlugin$Rules#createNativeBinaries(org.gradle.platform.base.
    BinaryContainer, org.gradle.api.NamedDomainObjectSet<org.gradle.nativeplatform.N
    ativeComponentSpec>, org.gradle.language.base.internal.registry.LanguageTransfor
    mContainer, org.gradle.nativeplatform.toolchain.internal.NativeToolChainRegistry
    Internal, org.gradle.platform.base.internal.PlatformResolvers, org.gradle.native
    platform.BuildTypeContainer, org.gradle.nativeplatform.FlavorContainer, org.grad
    le.internal.service.ServiceRegistry, java.io.File, org.gradle.api.internal.proje
    ct.taskfactory.ITaskFactory)
       > Unknown native toolchain: org.gradle.nativeplatform.toolchain.internal.Defa
    ultNativeToolChainRegistry$UnavailableNativeToolChain
    
    * Try:
    Run with --stacktrace option to get the stack trace. Run with --info or --debug
    option to get more log output.
    
    BUILD FAILED
    
    Total time: 7.285 secs

I, honestly, do not understand a thing and do not get any `build/binaries/` folder anywhere.

**Comment by fred0r** [comment]
```
java.io.IOException: Cannot run program "bash" (in directory "C:\Users\Marko"):
CreateProcess error=2, The system cannot find the file specified
```
Why do you want to build it?

**Comment by Uberwire** [comment]
Nevermind, just found out about the msvc folder.
