### ISSUE TITLE
Crash in UpdateClientData(edict_s const*, int, clientdata_s*) () from /home/server3367/game/cstrike/dlls/cs.so

### ISSUE THREAD

**Issue by jobmail** [s1lentq/ReGameDLL_CS#957]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `./hlds_linux -game cstrike +ip 62.122.213.230 +port 27015 +map de_dust2 +maxpla'.
Program terminated with signal 11, Segmentation fault.
#0  0x00000000 in ?? ()
#0  0x00000000 in ?? ()
#1  0xb2a7f28b in UpdateClientData(edict_s const*, int, clientdata_s*) () from /home/server3367/game/cstrike/dlls/cs.so
#2  0xb1394494 in ?? ()
#3  0x00000005 in ?? ()
#4  0xb68a39a5 in SV_WriteClientdataToMessage () from /home/server3367/game/engine_i486.so
#5  0x0000019b in ?? ()
#6  0x0000019b in ?? ()
#7  0x00000016 in ?? ()
#8  0x00000001 in ?? ()
#9  0x00000000 in ?? ()

ReGameDLL version: 5.26.0.668-dev
Build date: 19:02:48 Dec 31 2023
Build from: https://github.com/s1lentq/ReGameDLL_CS/commit/d3c0ec8

ReHLDS version: 3.13.0.788-dev
Build date: 12:57:18 Jul 24 2023 (3390)
Build from: https://github.com/dreamstalker/rehlds/commit/f955b07

**Comment by hajimura** [comment]
You need to attach crashdump

**Comment by jobmail** [comment]
Hosting does not provide access to the dump file. Such errors (the ReHLDS+ReGame combination) began to appear regularly after updating ReGame to 5.26. The crash happens at a completely random time.
